language: node_js
node_js:
- '8'
script:
- npm run build
- npm run test
- npm run lint
- npm run test-coverage
- npm run codecov
- git checkout package-lock.json

cache:
  directories:
    - node_modules

