server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;   # React Router: SPA fallback
    }

    location /api/ {
        proxy_pass http://backend:3001;     # docker-compose verkkonimi
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }
}